### ISSUE TITLE
Upgrade to Elm 19.1

### ISSUE THREAD

**Issue by mksmtn** [kczulko/rules_elm#4]

**Comment by EdSchouten** [comment]
Feel free to submit PRs!

**Comment by kczulko** [comment]
Looks like it's done in https://github.com/kczulko/rules_elm/pull/10

Closing.

**Comment by kczulko** [comment]
Closed by mistake. I am trying to figure out what happened with *.elmi file as 0.19.1 doesn't generate them in case of elm_test target. More [here](https://discourse.elm-lang.org/t/lack-of-elmi-file-when-0-19-1-elm-version-is-used/9831).

**Comment by kczulko** [comment]
Ok, so it looks like this is actually more-less blocked by dropped support for elmi generation. In case of `elm_test` target, elm binary no longer produces elmi file. I have just discovered that both solutions `elm-test-rs` and `elm-test` are parsing file for searching possible test functions and this is probably what should be done here. See `Parser.js` and `check` function from `elm-test` node runner:
- https://github.com/rtfeldman/node-test-runner/blob/eedf853fc9b45afd73a0db72decebdb856a69771/elm/src/Test/Runner/Node.elm#L355
- https://github.com/rtfeldman/node-test-runner/blob/eedf853fc9b45afd73a0db72decebdb856a69771/lib/Generate.js#L179-L212
