### ISSUE TITLE
Adding an `elm_install` similar to rules_nodejs's `yarn_install`

### ISSUE THREAD

**Issue by jjant** [kczulko/rules_elm#9]
This might be just because I'm new to bazel, but it'd be a bit quite a bit simpler to have a rule to install elm libraries, just like `yarn_install`, from the project's `elm.json`.
Also, grabbing the elm compiler version from that would be good as well.

**Comment by EdSchouten** [comment]
Note that not using elm.json literally is somewhat on purpose. elm.json is very restrictive, in that there's no support for using alternative package repositories (e.g., internal mirrors), nor does it offer ways to fork core packages.

Declaring each of the dependencies in WORKSPACE using elm_repository() gives you more freedom to fetch code from arbitrary locations.

**Comment by kczulko** [comment]
I am closing the issue as author specified that this is intentional design.
